export const PREFERRED_ORDER = [
    "MSCI World Minimum Volatility (USD)",
    "MSCI World Momentum",
    "MSCI USA Small Cap Value Weighted",
    "Gold spot price",
    "FTSE World Government Bond - Developed Markets (Hedged EUR)",
    "Xtrackers II EUR Overnight Rate Swap (XEON)",
    "MSCI World Sector Neutral Quality",
];

export const DEFAULT_WEIGHTS: Record<string, number> = {
    "MSCI World Minimum Volatility (USD)": 0.35,
    "MSCI World Momentum": 0.25,
    "MSCI USA Small Cap Value Weighted": 0.10,
    "Gold spot price": 0.10,
    "FTSE World Government Bond - Developed Markets (Hedged EUR)": 0.10,
    "Xtrackers II EUR Overnight Rate Swap (XEON)": 0.10,
    "MSCI World Sector Neutral Quality": 0.00,
};

/**
 * Maps legacy or variant asset names to the current canonical names used in the data files.
 * This ensures that saved portfolios continue to work even if asset names are updated in process.py.
 */
export const ASSET_NAME_MAPPING: Record<string, string> = {
    "Managed Futures (DBMFE)": "DBMF (Managed Futures)",
    "iMGP DBi Managed Futures Fund": "DBMF (Managed Futures)",
    "DFA Global Equity (DGEIX)": "DGEIX (DFA Global Equity)",
    "WisdomTree Global Efficient Core (NTSG)": "NTSG (WisdomTree Global Efficient Core)",
};

export const ASSET_CATEGORY_OVERRIDES: Record<string, string> = {
    "MSCI World Minimum Volatility (USD)": "stocks",
    "MSCI World Momentum": "stocks",
    "MSCI USA Small Cap Value Weighted": "stocks",
    "MSCI World Sector Neutral Quality": "stocks",
    "FTSE World Government Bond - Developed Markets (Hedged EUR)": "bonds",
    "Xtrackers II EUR Overnight Rate Swap (XEON)": "cash",
    "Gold spot price": "gold",
    "iMGP DBi Managed Futures Fund": "alternatives",
    "Managed Futures (DBMFE)": "alternatives",
    "DBMF (Managed Futures)": "alternatives",
    "MSCI World Minimum Volatility (EUR)": "stocks",
    "Commodities (BCOM) (USD)": "alternatives",
    "Commodities (BCOM) (EUR)": "alternatives",
    "WisdomTree Enhanced Commodity (USD)": "alternatives",
    "WisdomTree Enhanced Commodity (EUR)": "alternatives",
    "L&G Multi-Strategy Enhanced Commodities (USD)": "alternatives",
    "L&G Multi-Strategy Enhanced Commodities (EUR)": "alternatives",
    "Bloomberg Roll Select Commodity (USD)": "alternatives",
    "Bloomberg Roll Select Commodity (EUR)": "alternatives",
    "UBS CMCI Composite Commodity (USD)": "alternatives",
    "UBS CMCI Composite Commodity (EUR)": "alternatives",
    "Dimensional Global Core Equity (DEGC) (USD)": "stocks",
    "Dimensional Global Core Equity (DEGC) (EUR)": "stocks",
};

export const IT_ANNUAL_CPI: Record<number, number> = {
    1994: 4.05, 1995: 5.23, 1996: 4.00, 1997: 2.04, 1998: 1.95, 1999: 1.66, 2000: 2.53,
    2001: 2.78, 2002: 2.46, 2003: 2.67, 2004: 2.20, 2005: 1.98, 2006: 2.09, 2007: 1.82,
    2008: 3.34, 2009: 0.77, 2010: 1.52, 2011: 2.78, 2012: 3.04, 2013: 1.21, 2014: 0.24,
    2015: 0.03, 2016: -0.09, 2017: 1.22, 2018: 1.13, 2019: 0.61, 2020: -0.13, 2021: 1.87,
    2022: 8.20, 2023: 5.62, 2024: 0.98, 2025: 1.8,
};

export const US_ANNUAL_CPI: Record<number, number> = {
    1994: 2.6, 1995: 2.8, 1996: 3.0, 1997: 2.3, 1998: 1.6, 1999: 2.2, 2000: 3.4,
    2001: 2.8, 2002: 1.6, 2003: 2.3, 2004: 2.7, 2005: 3.4, 2006: 3.2, 2007: 2.8,
    2008: 3.8, 2009: -0.4, 2010: 1.6, 2011: 3.2, 2012: 2.1, 2013: 1.5, 2014: 1.6,
    2015: 0.1, 2016: 1.3, 2017: 2.1, 2018: 2.4, 2019: 1.8, 2020: 1.2, 2021: 4.7,
    2022: 8.0, 2023: 4.1, 2024: 2.9, 2025: 2.0,
};

export const ASSET_TER_MAPPING: Record<string, number> = {
    "US Small Cap Value": 0.0030,
    "MSCI World": 0.0020,
    "MSCI World ACWI": 0.0020,
    "MSCI World ACWI IMI": 0.0017,
    "MSCI World IMI": 0.0017,
    "MSCI World Minimum Volatility": 0.0030,
    "MSCI World Momentum": 0.0025,
    "MSCI World Quality": 0.0025,
    "MSCI World Small Cap Value": 0.0039,
    "MSCI World Value": 0.0025,
    "Gold": 0.0012,
    "S&P 500 Total Return": 0.0007,
    "Nasdaq Total Return": 0.0030,
    "DFA Global Equity (DGEIX)": 0.0026,
    "DGEIX (DFA Global Equity)": 0.0026,
    "Dimensional Global Core Equity (DEGC)": 0.0026,
    "Managed Futures (DBMFE)": 0.0075,
    "DBMF (Managed Futures)": 0.0075,
    "WisdomTree Global Efficient Core (NTSG)": 0.0025,
    "NTSG (WisdomTree Global Efficient Core)": 0.0025,
    "EUR Government Bonds 10y": 0.0015,
    "Xtrackers II EUR Overnight Rate Swap (XEON)": 0.0010,
    "Japan": 0.0058,
    "Pacific": 0.0020,
    "Switzerland": 0.0020,
    "UK": 0.0033,
    "MSCI Emerging Markets IMI": 0.0018,
    "MSCI Emerging Market": 0.0018,
    "Commodities (BCOM)": 0.0030,
    "WisdomTree Enhanced Commodity": 0.0070,
    "L&G Multi-Strategy Enhanced Commodities": 0.0030,
    "Bloomberg Roll Select Commodity": 0.0028,
    "UBS CMCI Composite Commodity": 0.0034,
};

export const ASSET_CAPE_MAPPING: Record<string, number> = {
    "US Small Cap Value": 24.0,
    "MSCI World": 25.8,
    "MSCI World ACWI": 24.5,
    "MSCI World IMI": 24.2,
    "MSCI World Minimum Volatility": 22.1,
    "MSCI World Momentum": 34.2,
    "MSCI World Quality": 32.5,
    "MSCI World Small Cap Value": 18.5,
    "MSCI World Value": 19.2,
    "S&P 500 Total Return": 39.9,
    "Nasdaq Total Return": 42.5,
    "DFA Global Equity (DGEIX)": 24.8,
    "DGEIX (DFA Global Equity)": 24.8,
    "Dimensional Global Core Equity (DEGC)": 24.8,
    "MSCI Emerging Market": 18.9,
    "MSCI Emerging Markets IMI": 18.9,
    "Japan": 24.5,
    "Pacific": 21.0,
    "Switzerland": 20.5,
    "UK": 16.2,
    "DFA Emerging Markets": 18.5,
    "WisdomTree Global Efficient Core (NTSG)": 25.8,
    "NTSG (WisdomTree Global Efficient Core)": 25.8,
    "MSCI World Sector Neutral Quality": 32.5,
    "MSCI World Minimum Volatility (USD)": 22.1,
    "MSCI World Minimum Volatility (EUR)": 22.1,
    "MSCI USA Small Cap Value Weighted": 24.0,
};

export const ASSET_EXTERNAL_LINKS: Record<string, string> = {
    "US Small Cap Value": "https://www.ssga.com/ie/en_gb/intermediary/etfs/spdr-msci-usa-small-cap-value-weighted-ucits-etf-zprv-gy",
    "MSCI USA Small Cap Value Weighted": "https://www.ssga.com/ie/en_gb/intermediary/etfs/spdr-msci-usa-small-cap-value-weighted-ucits-etf-zprv-gy",
    "MSCI World": "https://www.ishares.com/uk/individual/en/products/251882/ishares-msci-world-ucits-etf-acc-fund",
    "MSCI World ACWI": "https://www.ishares.com/uk/individual/en/products/251850/ishares-msci-acwi-ucits-etf",
    "MSCI World ACWI IMI": "https://www.ssga.com/at/en_gb/intermediary/etfs/spdr-msci-all-country-world-investable-market-ucits-etf-acc-spyi-gy",
    "MSCI World Minimum Volatility": "https://www.ishares.com/uk/individual/en/products/251382/ishares-msci-world-minimum-volatility-ucits-etf",
    "MSCI World Minimum Volatility (USD)": "https://www.ishares.com/uk/individual/en/products/251382/ishares-msci-world-minimum-volatility-ucits-etf",
    "MSCI World Minimum Volatility (EUR)": "https://www.ishares.com/uk/individual/en/products/251382/ishares-msci-world-minimum-volatility-ucits-etf",
    "MSCI World Momentum": "https://www.ishares.com/uk/individual/en/products/270051/ishares-msci-world-momentum-factor-ucits-etf",
    "MSCI World Quality": "https://www.ishares.com/uk/individual/en/products/270054/ishares-msci-world-quality-factor-ucits-etf",
    "MSCI World Sector Neutral Quality": "https://www.ishares.com/uk/individual/en/products/270054/ishares-msci-world-quality-factor-ucits-etf",
    "MSCI World Small Cap Value": "https://www.avantisinvestors.com/ucitsetf/avantis-global-small-cap-value-ucits-etf/",
    "MSCI World Value": "https://www.ishares.com/uk/individual/en/products/270048/ishares-msci-world-value-factor-ucits-etf",
    "MSCI Emerging Markets IMI": "https://www.ishares.com/uk/individual/en/products/264659/ishares-msci-emerging-markets-imi-ucits-etf",
    "Gold": "https://www.ishares.com/uk/individual/en/products/258441/ishares-physical-gold-etc-fund",
    "Gold spot price": "https://www.ishares.com/uk/individual/en/products/258441/ishares-physical-gold-etc-fund",
    "S&P 500 Total Return": "https://www.ishares.com/uk/individual/en/products/253743/ishares-sp-500-b-ucits-etf-acc-fund",
    "Berkshire Hathaway": "https://finance.yahoo.com/quote/BRK-B/",
    "Nasdaq Total Return": "https://finance.yahoo.com/quote/QQQ/",
    "Managed Futures (DBMFE)": "https://www2.imgp.com/imgp-dbi-managed-futures-fund",
    "DBMF (Managed Futures)": "https://www2.imgp.com/imgp-dbi-managed-futures-fund",
    "iMGP DBi Managed Futures Fund": "https://www2.imgp.com/imgp-dbi-managed-futures-fund",
    "DFA Global Equity (DGEIX)": "https://www.dimensional.com/us-en/funds/dgeix/global-equity-portfolio-i",
    "DGEIX (DFA Global Equity)": "https://www.dimensional.com/us-en/funds/dgeix/global-equity-portfolio-i",
    "Dimensional Global Core Equity (DEGC)": "https://www.justetf.com/en/etf-profile.html?isin=IE000EGGFVG6",
    "DFA Emerging Markets": "https://www.dimensional.com/au-en/funds/dfemx/emerging-markets-portfolio-i",
    "WisdomTree Global Efficient Core (NTSG)": "https://www.wisdomtree.eu/en-gb/etfs/efficient-core/ntsg-wisdomtree-global-efficient-core-ucits-etf---usd-acc",
    "NTSG (WisdomTree Global Efficient Core)": "https://www.wisdomtree.eu/en-gb/etfs/efficient-core/ntsg-wisdomtree-global-efficient-core-ucits-etf---usd-acc",
    "EUR Government Bonds 10y": "https://www.ishares.com/uk/individual/en/products/251738/ishares-euro-government-bond-710yr-ucits-etf",
    "FTSE World Government Bond - Developed Markets (Hedged EUR)": "https://www.ishares.com/uk/individual/en/products/251738/ishares-euro-government-bond-710yr-ucits-etf",
    "Xtrackers II EUR Overnight Rate Swap (XEON)": "https://etf.dws.com/en-gb/LU0290358497-eur-overnight-rate-swap-ucits-etf-1c/",
    "Commodities (BCOM)": "https://www.invesco.com/uk/en/financial-products/etfs/invesco-bloomberg-commodity-ucits-etf.html",
    "WisdomTree Enhanced Commodity": "https://www.wisdomtree.eu/en-gb/etfs/commodities/wisdomtree-enhanced-commodity-ucits-etf-usd-acc",
    "L&G Multi-Strategy Enhanced Commodities": "https://fundcentres.landg.com/en/uk/adviser-wealth/fund-centre/ETF/Multi-Strategy-Enhanced-Commodities/?assetClass=Commodity",
    "Bloomberg Roll Select Commodity": "https://www.ishares.com/uk/individual/en/products/298008/ishares-bloomberg-enhanced-roll-yield-commodity-swap-ucits-etf",
    "UBS CMCI Composite Commodity": "https://www.ubs.com/fi/en/assetmanagement/funds/etf/ie00b53h0131-ubs-irl-fund-solutions-plc-cmci-composite-sf-ucits-etf-usd-a-acc-pd001.html"
};
